name: ultimate_flutter_project_template
description: "Ultimate Flutter Project Template with Clean Architecture, Riverpod, GoRouter, state management, offline support, and enterprise-ready structure."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.1.1
  cupertino_icons: ^1.0.8
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^10.0.0
  freezed_annotation: ^3.1.0
  go_router: ^17.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.2
  lottie: ^3.3.2
  riverpod_annotation: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/lottie/
    - assets/audio/
    - assets/videos/
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
