name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.13.0
        with:
          flutter-version: "3.13.7"
          channel: "stable"
          cache: false

      - name: Disable Flutter Analytics
        run: flutter config --no-analytics

      - name: Upgrade Flutter
        run: flutter upgrade --force

      - name: Check Flutter & Dart versions
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run unit tests
        run: flutter test test/unit

      - name: Run widget tests
        run: flutter test test/widget

      - name: Run integration tests
        run: flutter test test/integration

      # Optional: Build APK
      #- name: Build APK
      #  run: flutter build apk --release
